name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          
            - uses: actions/checkout@v4
            - name: Get Nightly Build
              run: rustup override set nightly
            - name: Add rust-src
              run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
            - name: Add llvm-tools 
              run: rustup component add llvm-tools-preview
            - name: Install Bootimage
              run: cargo install bootimage
            - name: Build
              run: cargo build --target x86_64-sketchOS.json --verbose
            - name: Run tests
              run: cargo test --target x86_64-sketchOS.json --verbose
