name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Get Nightly Build
              run: rustup override set nightly
            - name: Build Standard Library
              run: cargo build -Z build-std
            - name: Add Core
              run: rustup target add x86_64-sketchOS
            - name: Check Cargo Version
              run: cargo --version
            - name: Check rustc Version
              run: rustc --version
            - name: Build
              run: cargo build --verbose
            - name: Run tests
              run: cargo test --verbose
