name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Get Nightly Build
              run: rustup override set nightly
            - name: Add Rust Source
              run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
            - name: Check Cargo Version
              run: cargo --version
            - name: Check rustc Version
              run: rustc --version
            - name: Build
              run: cargo build --target x86_64-blog_os.json --verbose
            - name: Run tests
              run: cargo test --verbose
